### ISSUE TITLE
Is it possible to "throw" the screen and have it slowly decelerate?

### ISSUE THREAD

**Issue by soccerob** [Julian-Vos/asset-library-MapCamera2D-4#1]
Sorry if this is the wrong spot to suggest this, but I was wondering if it's possible to allow the screen to be thrown like you would expect on a mobile device, where the screen continues to move and then slows down to a stop.

Also, I'm not super familiar with Camera2D, but is it possible to have these effects only apply to the children nodes of the camera, and not to the entire scene?

Thanks

**Comment by Julian-Vos** [comment]
Hey, thank you for the great suggestion! I've just implemented it using a new exported variable `drag_inertia`. The higher you set it, the longer it takes for the drag movement to come to a stop. Asset library version 1.1.0 pending approval.

A `Camera2D` affects its canvas layer's viewport. Try adding your `Camera2D` node and the nodes you want to move along to a separate `CanvasLayer` or `SubViewport` node :)
