### ISSUE TITLE
When drag inertia > 0, the camera jumps a bit when the mouse stops moving and left click is released

### ISSUE THREAD

**Issue by stanchyk7** [Julian-Vos/asset-library-MapCamera2D-4#6]
The problem occurs when drag inertia is greater than 0.

**Expected behavior**: When the mouse stops moving and left click is released, the camera should stay in place.
**What happens instead**: When the mouse stops moving and left click is released, the camera jumps a bit.

**Additional notes**

While messing around with the script, I took a look into the Inspector and noticed that the _drag_movement variable doesn't set itself to 0 when the mouse stops moving.

A minimal reproduction project and a video showing the issue are provided below.

https://github.com/user-attachments/assets/d49f3d22-8362-40a7-ae8d-69d3bf07d082

[camera_drag_is_broken.zip](https://github.com/user-attachments/files/17602329/camera_drag_is_broken.zip)

**Comment by Julian-Vos** [comment]
Hello, thank you for your report :) From your description and video this seems like the intended behaviour: the camera comes to a halt immediately after dragging when `drag_inertia` is 0. It never comes to a halt when `drag_inertia` is 1. Any value between might be useful so that players can smoothly "throw" the camera a bit.

**Comment by stanchyk7** [comment]
Can you modify the script so that _drag_movement sets itself to 0 when the mouse stays in place regardless of drag inertia? I do want to throw the camera around.

**Comment by Julian-Vos** [comment]
It stays in place when there's no movement while releasing the left mouse button. You should be able to add some code at line 86 so that `_drag_movement` is set to 0 when there is very little movement, something like:
```
if _drag_movement.length() < 3:
    _drag_movement.x = 0
    _drag_movement.y = 0
```

**Comment by Julian-Vos** [comment]
Hey, it's been a while, but I've finally solved this problem for real. It didn't occur on my device (MacBook with trackpad), but a friend of mine had it too and it makes a lot of sense after all. I've just pushed an update to the script, which now only recognises throws that were quick and far enough. Asset Library version 1.2.2, pending approval!
